### ISSUE TITLE
Question: How to create a account?

### ISSUE THREAD

**Issue by kudlatiger** [so87/CISSP-Study-Guide#6]
Great resource, but one quick question. 

There is a link provided for free videos [https://fedvte.usalearning.gov/](https://fedvte.usalearning.gov/) but how do we create an account here? Is it only for government employees?

**Comment by so87** [comment]
yes only government employees or contractors. I had to sign up for an
account on that sight and put in my employee info

**Comment by kudlatiger** [comment]
Oh okay. we can close this question.
